name: Library

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

  #schedule:
  # Github Action 使用世界标准时间（UTC），北京时间（UTC+8）转换为世界标准时需要减去8小时
  #  - cron:  '01 0 * * *' # 默认在每天 UTC 00:01 （北京时间 8:01 ）执行 ----- 单个时间点
  # - cron:  '30 12,23 * * *' # 默认在每天 UTC 12:30 和 23:30 （北京时间 20:30 和 7:30）执行 ----- 多个时间点

jobs:
  USER_01:
    runs-on: ubuntu-latest
    environment: Library_CONFIG # 填写需要使用的用户配置对应的环境,请自行根据实际情况修改
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Import cache
      uses: actions/cache@v2
      with:
        path: .cache
        key: ${{ secrets.CACHE_NAME }}-${{ github.run_id }}
        restore-keys: ${{ secrets.CACHE_NAME }}-
    - name: Run script
      env:
        USERNAME: ${{secrets.USERNAME}}
        PASSWORD: ${{secrets.PASSWORD}}
        AREA_ID: ${{secrets.AREA_ID}}
        BANNED_SEAT: ${{secrets.BANNED_SEAT}}
        SELECT_WAY: ${{secrets.SELECT_WAY}}
        OK_SEAT: ${{secrets.OK_SEAT}}
        OTHERS_ACCOUNT_USERNAME_1: ${{secrets.OTHERS_ACCOUNT_USERNAME_1}}
        OTHERS_ACCOUNT_PASSWORD_1: ${{secrets.OTHERS_ACCOUNT_PASSWORD_1}}
        OTHERS_ACCOUNT_USERNAME_2: ${{secrets.OTHERS_ACCOUNT_USERNAME_2}}
        OTHERS_ACCOUNT_PASSWORD_2: ${{secrets.OTHERS_ACCOUNT_PASSWORD_2}}
        OTHERS_ACCOUNT_USERNAME_3: ${{secrets.OTHERS_ACCOUNT_USERNAME_3}}
        OTHERS_ACCOUNT_PASSWORD_3: ${{secrets.OTHERS_ACCOUNT_PASSWORD_3}}
        OTHERS_ACCOUNT_USERNAME_4: ${{secrets.OTHERS_ACCOUNT_USERNAME_4}}
        OTHERS_ACCOUNT_PASSWORD_4: ${{secrets.OTHERS_ACCOUNT_PASSWORD_4}}
        OTHERS_ACCOUNT_USERNAME_5: ${{secrets.OTHERS_ACCOUNT_USERNAME_5}}
        OTHERS_ACCOUNT_PASSWORD_5: ${{secrets.OTHERS_ACCOUNT_PASSWORD_5}}
        OTHERS_ACCOUNT_USERNAME_6: ${{secrets.OTHERS_ACCOUNT_USERNAME_6}}
        OTHERS_ACCOUNT_PASSWORD_6: ${{secrets.OTHERS_ACCOUNT_PASSWORD_6}}
        OTHERS_ACCOUNT_USERNAME_7: ${{secrets.OTHERS_ACCOUNT_USERNAME_7}}
        OTHERS_ACCOUNT_PASSWORD_7: ${{secrets.OTHERS_ACCOUNT_PASSWORD_7}}
        OTHERS_ACCOUNT_USERNAME_8: ${{secrets.OTHERS_ACCOUNT_USERNAME_8}}
        OTHERS_ACCOUNT_PASSWORD_8: ${{secrets.OTHERS_ACCOUNT_PASSWORD_8}}
        OTHERS_ACCOUNT_USERNAME_9: ${{secrets.OTHERS_ACCOUNT_USERNAME_9}}
        OTHERS_ACCOUNT_PASSWORD_9: ${{secrets.OTHERS_ACCOUNT_PASSWORD_9}}
        OTHERS_ACCOUNT_USERNAME_10: ${{secrets.OTHERS_ACCOUNT_USERNAME_10}}
        OTHERS_ACCOUNT_PASSWORD_10: ${{secrets.OTHERS_ACCOUNT_PASSWORD_10}}
        ALWAYS_SPARE_AREA: ${{secrets.ALWAYS_SPARE_AREA}}
        BARK_TOKEN: ${{secrets.BARK_TOKEN}}
        DD_BOT_ACCESS_TOKEN: ${{secrets.DD_BOT_ACCESS_TOKEN}}
        DD_BOT_SECRET: ${{secrets.DD_BOT_SECRET}}
      run: python main.py
